# Generated by Django 5.2a1 on 2025-02-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
        ('wish_list', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wishlistitem',
            constraint=models.UniqueConstraint(fields=('wish_list', 'product'), name='unique_wishlist_product'),
        ),
    ]
