# Generated by Django 5.2a1 on 2025-02-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='total_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsize',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsize',
            name='number_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
