# Generated by Django 5.2a1 on 2025-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_in_stock_product_total_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
