# Generated by Django 5.2a1 on 2025-05-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_total_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
